db:
  CHECK_SMEV:
    host: "127.0.0.1"
    port: "5432"
    user: "test"
    dbname: "logging"
    sslmode: "disable"
  DPO:
    host: "127.0.0.1"
    port: "5432"
    user: "test"
    dbname: "dpo"
    sslmode: "disable"
rabbitMq:
  host:  "127.0.0.1"
  login: "test"
  vHost: "/"
  queuesOut:
    alias:      "OUT"
    exchange:   "out.test"
    routingKey: "input"
  queuesIn:
    alias:      "IN"
    remoteKoef: 15
    queue:      "in.test.output"
